# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1 
  - 1.2
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
